/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swingy;

/**
 *
 * @author GlintSolutions
 */
public class createPlayer extends javax.swing.JFrame {

    /**
     * Creates new form createPlayer
     */
    public createPlayer() {
        initComponents();
    }
    SwingyJF prev;

    createPlayer(SwingyJF aThis) {
        initComponents();
        prev = aThis; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitBTN = new javax.swing.JButton();
        backBTN = new javax.swing.JButton();
        heroNameLBL = new javax.swing.JLabel();
        HeroNameTBX = new javax.swing.JTextField();
        weaponOfChoice = new javax.swing.JLabel();
        weaponCBX = new javax.swing.JComboBox<>();
        heroClassLBL = new javax.swing.JLabel();
        heroClassCBX = new javax.swing.JComboBox<>();
        protectiveArmorCBX = new javax.swing.JComboBox<>();
        protectiveArmorLBL = new javax.swing.JLabel();
        helmLBL = new javax.swing.JLabel();
        helmCBX = new javax.swing.JComboBox<>();
        attackLBL = new javax.swing.JLabel();
        defenceLBL = new javax.swing.JLabel();
        attackTxtLbl = new javax.swing.JLabel();
        defenceTxtLbl = new javax.swing.JLabel();
        imageLBL = new javax.swing.JLabel();
        hitPointsLBL = new javax.swing.JLabel();
        hitPointsTxtLbl = new javax.swing.JLabel();
        createHeroLBL = new javax.swing.JLabel();
        ceateHeroBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));
        setPreferredSize(new java.awt.Dimension(700, 300));
        setSize(new java.awt.Dimension(700, 300));

        exitBTN.setText("exit");
        exitBTN.setToolTipText("exit app");
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });

        backBTN.setText("back");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });

        heroNameLBL.setText("Hero Name");

        weaponOfChoice.setText("weapon of choice");

        weaponCBX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Slayer's Exe", "sword of the lord's charm", "black fury spear", "arieliunous bow", "twigs twin blades" }));

        heroClassLBL.setText("Hero class");

        heroClassCBX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Knight", "BlackMagicWarrior", "shadower", " " }));

        protectiveArmorCBX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "granny's cat", "rynxGlove", "ridpants", "knightOfWands", "knightOfValor" }));

        protectiveArmorLBL.setText("Armor of choice");

        helmLBL.setText("helm");

        helmCBX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "gogo'sMagic", "KZNSpecial", "limpopoGlory" }));

        attackLBL.setText("Attack");

        defenceLBL.setText("Defense");

        attackTxtLbl.setBackground(new java.awt.Color(204, 255, 204));
        attackTxtLbl.setFont(new java.awt.Font("Lucida Handwriting", 3, 18)); // NOI18N
        attackTxtLbl.setText("Attack");

        defenceTxtLbl.setBackground(new java.awt.Color(255, 204, 204));
        defenceTxtLbl.setFont(new java.awt.Font("Lucida Handwriting", 3, 18)); // NOI18N
        defenceTxtLbl.setText("Attack");

        imageLBL.setBackground(new java.awt.Color(0, 102, 102));
        imageLBL.setFont(new java.awt.Font("Lucida Handwriting", 3, 18)); // NOI18N

        hitPointsLBL.setText("hit points");

        hitPointsTxtLbl.setBackground(new java.awt.Color(204, 204, 255));
        hitPointsTxtLbl.setFont(new java.awt.Font("Lucida Handwriting", 3, 18)); // NOI18N
        hitPointsTxtLbl.setText("Attack");

        createHeroLBL.setBackground(new java.awt.Color(204, 255, 255));
        createHeroLBL.setFont(new java.awt.Font("Broadway", 1, 24)); // NOI18N
        createHeroLBL.setForeground(new java.awt.Color(102, 102, 102));
        createHeroLBL.setText("create hero");
        createHeroLBL.setFocusable(false);

        ceateHeroBTN.setText("create Hero");
        ceateHeroBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceateHeroBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(116, 116, 116)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(attackLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(attackTxtLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(64, 64, 64))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(heroNameLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(HeroNameTBX, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(70, 70, 70)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(defenceLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(hitPointsLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(defenceTxtLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(hitPointsTxtLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(weaponCBX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(helmLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(helmCBX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(weaponOfChoice)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addComponent(ceateHeroBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imageLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(heroClassCBX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(protectiveArmorLBL)
                                    .addComponent(protectiveArmorCBX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(createHeroLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(253, 253, 253)
                                .addComponent(heroClassLBL))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(backBTN)
                                .addGap(574, 574, 574)
                                .addComponent(exitBTN)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(7, 7, 7))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createHeroLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(protectiveArmorLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(protectiveArmorCBX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(heroClassLBL)
                            .addComponent(weaponOfChoice))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(weaponCBX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(heroClassCBX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(imageLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(heroNameLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(HeroNameTBX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(helmLBL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(helmCBX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(89, 89, 89)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(defenceLBL)
                                        .addComponent(attackLBL))
                                    .addComponent(hitPointsLBL))
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(defenceTxtLbl)
                                        .addComponent(attackTxtLbl))
                                    .addComponent(hitPointsTxtLbl))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ceateHeroBTN)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backBTN)
                    .addComponent(exitBTN)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
     System.exit(0);
    }//GEN-LAST:event_exitBTNActionPerformed

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        prev.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBTNActionPerformed

    private void ceateHeroBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceateHeroBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ceateHeroBTNActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(createPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(createPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(createPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(createPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new createPlayer().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField HeroNameTBX;
    private javax.swing.JLabel attackLBL;
    private javax.swing.JLabel attackTxtLbl;
    private javax.swing.JButton backBTN;
    private javax.swing.JButton ceateHeroBTN;
    private javax.swing.JLabel createHeroLBL;
    private javax.swing.JLabel defenceLBL;
    private javax.swing.JLabel defenceTxtLbl;
    private javax.swing.JButton exitBTN;
    private javax.swing.JComboBox<String> helmCBX;
    private javax.swing.JLabel helmLBL;
    private javax.swing.JComboBox<String> heroClassCBX;
    private javax.swing.JLabel heroClassLBL;
    private javax.swing.JLabel heroNameLBL;
    private javax.swing.JLabel hitPointsLBL;
    private javax.swing.JLabel hitPointsTxtLbl;
    private javax.swing.JLabel imageLBL;
    private javax.swing.JComboBox<String> protectiveArmorCBX;
    private javax.swing.JLabel protectiveArmorLBL;
    private javax.swing.JComboBox<String> weaponCBX;
    private javax.swing.JLabel weaponOfChoice;
    // End of variables declaration//GEN-END:variables
}
