/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swingy;

/**
 *
 * @author GlintSolutions
 */
public class SwingyJF extends javax.swing.JFrame {

    /**
     * Creates new form SwingyJF
     */
    public SwingyJF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitBTN = new javax.swing.JButton();
        startAdventureBTN = new javax.swing.JButton();
        selectPlayerBTN = new javax.swing.JButton();
        createPlayerBTN = new javax.swing.JButton();
        welcomeLBL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        setLocation(new java.awt.Point(200, 200));
        setName("startScreen"); // NOI18N
        setPreferredSize(new java.awt.Dimension(700, 370));
        setSize(new java.awt.Dimension(700, 370));

        exitBTN.setForeground(new java.awt.Color(255, 51, 51));
        exitBTN.setText("exit");
        exitBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitBTN.setName("exitBTN"); // NOI18N
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });

        startAdventureBTN.setBackground(new java.awt.Color(204, 255, 255));
        startAdventureBTN.setFont(new java.awt.Font("Trajan Pro", 3, 14)); // NOI18N
        startAdventureBTN.setForeground(new java.awt.Color(0, 102, 102));
        startAdventureBTN.setText("Start Adventure");
        startAdventureBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        startAdventureBTN.setName("StartAdventureBTN"); // NOI18N
        startAdventureBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startAdventureBTNActionPerformed(evt);
            }
        });

        selectPlayerBTN.setBackground(new java.awt.Color(204, 255, 255));
        selectPlayerBTN.setFont(new java.awt.Font("Trajan Pro", 3, 14)); // NOI18N
        selectPlayerBTN.setForeground(new java.awt.Color(0, 102, 102));
        selectPlayerBTN.setText("select Player");
        selectPlayerBTN.setToolTipText("select previously crated Hero");
        selectPlayerBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        selectPlayerBTN.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        selectPlayerBTN.setName("CreatePlayerBTN"); // NOI18N
        selectPlayerBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectPlayerBTNActionPerformed(evt);
            }
        });

        createPlayerBTN.setBackground(new java.awt.Color(204, 255, 255));
        createPlayerBTN.setFont(new java.awt.Font("Trajan Pro", 3, 14)); // NOI18N
        createPlayerBTN.setForeground(new java.awt.Color(0, 102, 102));
        createPlayerBTN.setText("Create Player");
        createPlayerBTN.setToolTipText("create a new Hero");
        createPlayerBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createPlayerBTN.setName("CreatePlayerBTN"); // NOI18N
        createPlayerBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPlayerBTNActionPerformed(evt);
            }
        });

        welcomeLBL.setBackground(new java.awt.Color(204, 255, 255));
        welcomeLBL.setFont(new java.awt.Font("Broadway", 1, 24)); // NOI18N
        welcomeLBL.setForeground(new java.awt.Color(102, 102, 102));
        welcomeLBL.setText("Welcome to the Advantures of  Swingy");
        welcomeLBL.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitBTN)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(welcomeLBL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(createPlayerBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selectPlayerBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(startAdventureBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(welcomeLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createPlayerBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startAdventureBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectPlayerBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(exitBTN)
                .addContainerGap())
        );

        exitBTN.getAccessibleContext().setAccessibleName("exitBTN");
        startAdventureBTN.getAccessibleContext().setAccessibleName("StartAdventure");
        createPlayerBTN.getAccessibleContext().setAccessibleName("CreatePlayer");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createPlayerBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPlayerBTNActionPerformed
        new createPlayer(this).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_createPlayerBTNActionPerformed

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitBTNActionPerformed

    private void selectPlayerBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectPlayerBTNActionPerformed
        new selectPlayer(this).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_selectPlayerBTNActionPerformed

    private void startAdventureBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startAdventureBTNActionPerformed
        new playGame(this).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_startAdventureBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SwingyJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SwingyJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SwingyJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SwingyJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SwingyJF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createPlayerBTN;
    private javax.swing.JButton exitBTN;
    private javax.swing.JButton selectPlayerBTN;
    private javax.swing.JButton startAdventureBTN;
    private javax.swing.JLabel welcomeLBL;
    // End of variables declaration//GEN-END:variables
}
